# -*- coding: utf-8 -*-
"""D27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQQvB6VGPbtfQ-33FNjYjiGG18bgyDDv
"""

!pip install dnspython
!pip install pymongo[srv]
import pymongo
client = pymongo.MongoClient("mongodb+srv://arunkumar:1234@cluster0.kvcpn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.mong
records=db.mongcolle
for i in range(1,4):
    name = ""
    mobile = 0
    emailid = ""

    n = input("Enter your name :")
    cap = n.capitalize()
    name = cap

    while True:
        m = input("Enter your mobile number: ")
        if m.isdigit() and len(m) == 10:
            mobile = m
            break
        else:
            print("please enter a correct mobile number")
            continue

    while True:
        u = input("  Enter your email id ")
        x = list(map(str, u))
        if "@" in x and "." in x and x[0].isalpha():
            y = u.split("@")
            z = list(map(str, y[1]))
            l = y[1].split(".")
            if l[0].isalpha() or l[0].isalnum():
                emailid = u
                break
            else:
                print("-------Enter a your email id correctly------ ")

        else:
            print("-------Enter a your email id correctly------ ")
            continue
    dict = {"_id": 0,
            "names": "",
            "mobiles": "",
            "emailids": ""}
    dict["_id"] = i
    dict["names"] = name
    dict["mobiles"] = mobile
    dict["emailids"] = emailid
    records.insert_one(dict)
    print("Successfully saved in the database ")

!pip install dnspython
!pip install pymongo[srv]
import pymongo
client = pymongo.MongoClient("mongodb+srv://arunkumar:1234@cluster0.kvcpn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.mong
records=db.mongcoll
id=1
name=""
mobile=0
emailid=""

n=input("Enter your name :")
cap = n.capitalize()
name = cap

while True:
    m = input("Enter your mobile number: ")
    if m.isdigit() and len(m) == 10:
        mobile = m
        break
    else:
        print("please enter a correct mobile number")
        continue


while True:
    u = input("  Enter your email id ")
    x = list(map(str, u))
    if "@" in x and "." in x and x[0].isalpha():
        y = u.split("@")
        z = list(map(str, y[1]))
        l = y[1].split(".")
        if l[0].isalpha() or l[0].isalnum():
            emailid=u
            break
        else:
            print("-------Enter a your email id correctly------ ")

    else:
        print("-------Enter a your email id correctly------ ")
        continue
dict={"_id":0,
"names":"",
"mobiles":"",
"emailids":""}
dict["_id"]=id
dict["names"]=name
dict["mobiles"]=mobile
dict["emailids"]=emailid
records.insert_one(dict)
print("Successfully saved in the database ")

x,y=map(int,input().split())
z=list(map(int,input().split()))
a=z
for i in range(y):
  b=a.pop()
  a.insert(0,b)
else:
  print(*a)

x,y=map(str,input().split())
z=y[::-1]
if len(x)==len(y) and y==z:
  print("1")
else:
  print("0")

x=int(input())
k=[]
for i in range(x):
  a=input()
  k.append(sorted(a))
else:
  print(*k)

import re
pattern="[a-zA-Z0-9]+@[a-zA-Z]+[\.][a-z]{2,3}"
x=input()
if re.search(pattern,x):
  print("yes")
else:
  print("no")

import re
def fun(email):
    if re.fullmatch(regex, email):
      print("Valid email")
    else:
      print("Invalid email")

regex = re.compile(r'([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+')
email=input()
fun(email)

import re
pattern="[a-zA-Z0-9]+@[a-zA-Z]+\(.com)"
x=input()
if (re.search(pattern,x)):
  print("yes")
else:
  print("no")

x,y=map(int,input().split())

#Inserting Image into mongo
from pymongo import MongoClient
from PIL import Image
import io
 
#<include your own connectio string>
import pymongo
client = pymongo.MongoClient("mongodb+srv://arunkumar:1234@cluster0.kvcpn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.d27
records=db.d27coll
 
im = Image.open("/content/ms-dhoni.jpg")
 
image_bytes = io.BytesIO()
im.save(image_bytes, format='JPEG')
 
image = {
   "name":"nethaji",
   'image': image_bytes.getvalue()
}
 
image_id = records.insert_one(image)



x,y=map(int,input().split())
for i in range(x):
    for j in range(y):
        print("*",end=" ")
    print()
* * * * *
* * * * *
* * * * *

from PIL import Image
kk= Image.open("/content/ms-dhoni.jpg")
kk

image_bytes.getvalue()

from pymongo import MongoClient
from PIL import Image
import io
 
#<include your own connectio string>
import pymongo
client = pymongo.MongoClient("mongodb+srv://arunkumar:1234@cluster0.kvcpn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.d27
records=db.d27coll
 
image = records.find_one({"name":"nethaji"}) 

img = Image.open(io.BytesIO(image["image"]))
img

for y in records.find():
  print(y)

for i in records.find({},{"name":1,'age':1,"_id":0}):
  print(i)

while True:
  x=int(input())
  if x==1:
    print(x)
    break
else:
  print("enter 1 ")

i = 1
while i < 6:
  print(i)
  i += 1
  if i==4:
    break
else:
  print("i is no longer less than 6")

!pip install dnspython
!pip install pymongo[srv]

import pymongo
client = pymongo.MongoClient("mongodb+srv://arunkumar:1234@cluster0.kvcpn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.d27
records=db.d27coll



B={"name":input("enter your name"),
     "age":int(input("enter your age")),
     "gender":input("enter your gender")}
records.insert_one(B)

print(db.list_collection_names())

mylist=[
         {"name": "arun","age":28,"gender":"male"},
         {"name": "kumar","age":31,"gender":"male"},
         {"name": "tamanna","age":28,"gender":"female"},
         {"_id":2,"name":"shriya","address":"mumbai"}

]
x=records.insert_many(mylist)
print(x.inserted_ids)

dbb=client.guvi
arun=dbb.guvimongo
B={"name": "aKR",
     "age":10,
     "gender":"male"}
arun.insert_one(B)

import json
x='{"name":"arun","age":28,"city":"KGF"}'
y=json.loads(x)
print(y)
print(y["age"])
y

import json
x={"name":"arun","age":28,"city":"KGF"}
y=json.dumps(x)
print(y)
y

di={"name": "arun",
     "age":10,
     "gender":"male"}
records.insert_one(di)

import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/titanic_train.csv")
df.isnull().sum()
df["Age"].fillna(method="ffill",inplace=True)
df.isnull().sum()

import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/titanic_train.csv")
#print(df.iloc[1:5,0:3])
#print(df.shape)
#print(df.plot.pie(y="Survived"))
#d=pd.DataFrame(df["Survived"])
#df["Fare"].hist(bins=100)
#df.boxplot()
#print(df.iloc[[1]])
#df["Age"].hist(bins=20)
d1=df["Sex"].replace("male",1)
d1.replace("female",2)
d2=pd.DataFrame(d1)
print(d2)

#print(df.isnull().any())
de=df.dropna()
de
#df.sort_values(by=["Fare"]),ascending=False
df

#df["Age"].fillna(method="ffill",inplace=True)
df.isnull().sum()

import pandas as pd
import numpy as np
data={"year":[10,11,12,11,11,12,13,11],
      "teams":["csk","mi","mi","srh","kkr","csk","csk","csk"],
      "wins":[11,8,10,15,11,6,10,4],
      "losses":[5,8,6,1,5,10,16,11]}
ipl=pd.DataFrame(data)
#print(ipl.plot.pie(y="wins"))
#ipl.hist(bins=100)
ipl.shape
ipl.size
ipl.sort_values(by=["losses"],ascending=True)
ipl.mul(3)["wins"]
ipl.to_csv("bb.csv")
ipl.drop(columns="year")
ipl["teams"].unique()
ipl.drop(index=0)

#finding subarrays

x=input()
y=len(x)

k=[]
for i in range(0,y+1):
  for j in range(i,y+1):
    a=x[i:j]
    k.append(a)
l=[]
for i in k:
  a=set(i)
  a=list(a)
  if len(i)==len(a):
    l.append(i)
h=[]
for i in l:
  b=len(i)
  h.append(b)
print(max(h))

import pandas as pd
import numpy as np
data={"year":[10,11,12,11,11,12,13,11],
      "teams":["csk","mi","mi","srh","kkr","csk","csk","csk"],
      "wins":[11,8,10,15,11,6,10,4],
      "losses":[5,8,6,1,5,10,16,11]}
ipl=pd.DataFrame(data)
#print(ipl.plot.pie(y="wins"))
#ipl.hist(bins=100)
ipl.shape
ipl.size
ipl.sort_values(by=["losses"],ascending=True)
ipl.mul(3)["wins"]
ipl.to_csv("bb.csv")
ipl.drop(columns="year")
ipl["teams"].unique()
ipl.drop(index=0)

import pandas as pd
s=pd.Series()
print(s)



!pip install pillow

np.savetxt("netu.txt",a)

np.load("/content/netu.txt")

c=np.array([1,2,3,4])
d=[1,2,4,5]
np.sqrt(c)
np.log(10)
np.sum(c)

import numpy as np
import pandas as pd
a=np.array(["a","b","c","d"])
b=pd.Series(a,index=[100,101,102,103])
print(a)
print(b)

a=np.random.random((3,2))

np.save("netgu",a)

np.load("/content/netgu.npy")

import openpyxl
from openpyxl import Workbook
wb = Workbook()
sh1 = wb.active
def fun1(register):
    username = []
    while register == "yes":
        u = input("  Enter your email id to register: ")
        x = list(map(str, u))
        if "@" in x and "." in x and x[0].isalpha():
            y = u.split("@")
            z = list(map(str, y[1]))
            l = y[1].split(".")
            if l[0].isalpha() or l[0].isalnum():
                username.append(u)
                break
            else:
                print("-------Enter a your email id correctly------ ")

        else:
            print("-------Enter a your email id correctly------ ")
            continue
    sh1.cell(row=1, column=1).value = username[0]
    wb.save("registration.xlsx")
    return username
def fun2(register):
    password = []
    while register == "yes":
        print("\n")
        print("please check the below points before setting up your password")
        print("\n")
        print("1. Must have minimum one special character")
        print("2. Must have minimum one digit")
        print("3. Must have minimum one uppercase")
        print("4. Must have minimum one lowercase")
        print("5. Password length must be between 5 and 16")
        print("\n")
        u = input("  Enter your password to register: ")
        x = list(map(str, u))
        w=len(x)
        lower = 0
        upper = 0
        num=0
        sp=0
        for i in x:
            if i.isupper():
                upper += 1
            elif i.islower():
                lower+= 1
            elif i.isdigit():
                num+=1
            else:
                sp+=1
        if w>5 and w<16 and lower!=0 and upper != 0 and sp!=0 and num!=0:
            password.append(u)
            break
        else:
            print("-------Enter a your password correctly------ ")
            continue
    sh1.cell(row=1, column=2).value = password[0]
    wb.save("registration.xlsx")
    return password



register=input(" Do you want to register?   yes or no :")
if register=="yes":
    username = fun1(register)
    password = fun2(register)


login=input(" Do you want to login yes or no :")
if login=="yes":
    a=input("enter username")
    b=input("enter password")
    wb1=openpyxl.load_workbook("registration.xlsx")
    sh2=wb1.active
    data1=sh2.cell(row=1, column=1).value
    data2=sh2.cell(row=1, column=2).value
    if a==data1 and b==data2:
        print("you have logged in sucessfully")
    elif a!=data1 and b!=data2:
        print("Invaild username or password")
        print(" Try to register before loging in")
        x = input("Do you want to register? yes or no :")
        if x == "yes":
            fun1(x)
            fun2(x)
elif login=="no":
    e = input("forget password yes or no :")
    if e == "yes":
        f = input("enter your username :")
        wb3 = openpyxl.load_workbook("registration.xlsx")
        sh3 = wb3.active
        data11 = sh3.cell(row=1, column=1).value
        data22 = sh3.cell(row=1, column=2).value
        if f==data11:
            print("your password is:",data22)
        else:
            print("-----sorry Wrong username-----")

ipl.boxplot()

import pandas as pd
s=pd.Series()
print(s)

import numpy as np
np.savetext("a.txt",a)



np.savetext("a.txt",a)

import pandas as pd
s=pd.Series([1,2,3],index=['a','b','c'])
print(s[a])

import pandas as pd
data=[["guvi 1",10],["guvi2",12],["guvi3",13]]
df=pd.DataFrame(data,columns=['name','age'],dtype=float)
print(df)

import pandas as pd
d={"year":[2010,2011,2012,2010,2102,2102,2012],
       "team":["df","fk","dkmf","dfm","dmf","df","dn"],
       "wins":[11,8,1,2,3,4,2],
       "loss":[1,2,3,4,3,4,6]}
ipl=pd.DataFrame(d)

#ipl.shape
#ipl.sort_values(by=["wins"],ascending=True)
#ipl.to_json("arun.json")
#ipl["year"
ipl.drop(rows="1")

import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/titanic_train.csv")
#df
#df
#a=pd.DataFrame(df["Survived"])
df.isnull().any()
de=df.dropna()
de.shape
de.size

import pandas as pd

ipl.head()
ipl.tail()

a=np.array([1,2,3])
b=[1,2,3]
np.add(a,b)

from openpyxl import Workbook
wb=Workbook()
sh1=wb.active
sh1.cell(row=1,column=1).value=input("enter email id:")
wb.save("registration.xlsx")
print(sh1.cell(row=1,column=1).value)



def fun1(register):
    username = []
    while register == "yes":
        u = input("  Enter your email id to register: ")
        x = list(map(str, u))
        if "@" in x and "." in x and x[0].isalpha():
            y = u.split("@")
            z = list(map(str, y[1]))
            l = y[1].split(".")
            if l[0].isalpha() or l[0].isalnum():
                username.append(u)
                break
            else:
                print("-------Enter a your email id correctly------ ")

        else:
            print("-------Enter a your email id correctly------ ")
            continue
    f = open("user.txt", "a")
    for i in username:
        f.write( i + "\n")
    f.close()
    return username
def fun2(register):
    password = []
    while register == "yes":
        print("\n")
        print("please check the below points before setting up your password")
        print("\n")
        print("1. Must have minimum one special character")
        print("2. Must have minimum one digit")
        print("3. Must have minimum one uppercase")
        print("4. Must have minimum one lowercase")
        print("5. Password length must be between 5 and 16")
        print("\n")
        u = input("  Enter your password to register: ")
        x = list(map(str, u))
        w=len(x)
        lower = 0
        upper = 0
        num=0
        sp=0
        for i in x:
            if i.isupper():
                upper += 1
            elif i.islower():
                lower+= 1
            elif i.isdigit():
                num+=1
            else:
                sp+=1
        if w>5 and w<16 and lower!=0 and upper != 0 and sp!=0 and num!=0:
            password.append(u)
            break
        else:
            print("-------Enter a your password correctly------ ")
            continue
    f = open("pass.txt", "a")
    for i in password:
        f.write(i + "\n")
    f.close()
    return password



register=input(" Do you want to register?   yes or no :")
username=fun1(register)
password=fun2(register)

login=input(" Do you want to login yes or no :")
if login=="yes":
    fr=open("user.txt","r")
    fr1=open("pass.txt","r")
    a=input("Enter your username :")
    b=input("Enter your password:")
    c=fr.read()
    d=fr1.read()
    if a in c:
        if b in d:
            in1 = c.index(a)
            in2 = d.index(b)
            print(in1)
            print(in2)
            if in1 == in2:
                print("You have logged in sucessfully")
                fr.close()
                fr1.close()

    else:
        fr.close()
        fr1.close()
        print("Username not found.Please register to login ")
        d = input("Do you want to register")
        if d == "yes":
            fun1(d)
            fun2(d)
        elif d == "no":
            e = input("forget password yes or no :")
            if e == "yes":
                f = input("enter your username :")
                br=open("user.txt","r")
                br1=open("pass.txt","r")
                aa=br.readline()
                bb=br1.readline()
                cc=aa.index(f)
                dd=bb.index("Prem@1986")

f=("/content/reg.xlsx")
wb=xlrd.open_workbook(f)

def fun1(register):
    username = []
    while register == "yes":
        u = input("  Enter your email id to register: ")
        x = list(map(str, u))
        if "@" in x and "." in x and x[0].isalpha():
            y = u.split("@")
            z = list(map(str, y[1]))
            l = y[1].split(".")
            if l[0].isalpha() or l[0].isalnum():
                username.append(u)
                break
            else:
                print("-------Enter a your email id correctly------ ")

        else:
            print("-------Enter a your email id correctly------ ")
            continue
    return username
def fun2(register):
    password = []
    while register == "yes":
        u = input("  Enter your password to register: ")
        x = list(map(str, u))
        w=len(x)
        lower = 0
        upper = 0
        num=0
        sp=0
        for i in x:
            if i.isupper():
                upper += 1
            elif i.islower():
                lower+= 1
            elif i.isdigit():
                num+=1
            else:
                sp+=1
        if w>5 and w<16 and lower!=0 and upper != 0 and sp!=0 and num!=0:
            password.append(u)
            break
        else:
            print("-------Please try again and check the above 5 points before setting up your password------ ")
            continue
    return password



register=input(" Do you want to register?   yes or no :")
username=fun1(register)
print("\n")
print("please check the below 5 points before setting up your password")
print("\n")
print("1. Must have minimum one special character")
print("2. Must have minimum one digit")
print("3. Must have minimum one uppercase")
print("4. Must have minimum one lowercase")
print("5. Password length must be between 5 and 16")
print("\n")
password=fun2(register)
print(*username)
print(*password)


login=input(" Do you want to login yes or no :")

f1=open("file1.txt","w")

register=input(" Do you want to register?   yes or no :")
while register == "yes":
    u = input("  Enter your email id to register: ")
    username = []
    x = list(map(str, u))
    if "@" in x and "." in x and x[0].isalpha():
        y = u.split("@")
        z = list(map(str, y[1]))
        l = y[1].split(".")
        if l[0].isalpha() or l[0].isalnum():
            username.append(u)
            break
        else:
            print("-------Enter a your correct email id to register------ ")

    else:
        print("-------Enter a your correct email id to register------ ")
        continue
    p=input(" enter pass")

while register =="no":
  login=input(" Do you want to login yes or no :")



x=input()
if 5<len(x)>7:
  print(x)

name=[]
mob=[]
email=[]
n=int(input("enter total no of contacts to be stored : "))
for i in range(n):
    a=input("enter name:")
    name.append(a.capitalize())
    while True:
        b = input("enter mobile number :")
        if len(b) == 10 and b.isdigit():
            mob.append(b)
            break
        else:
            print("----enter a correct mobile number----")
            continue

    while True:
        e = input("enter email id :")
        l=list(map(str,e))
        c = e.split("@")
        if "@" in l and "gmail.com" in c and c[0].isalpha():
            email.append(e)
            break
        else:
            print("-----enter a correct e-mailid of gmail account-----")
            continue

# search person contact details
a=input("search contact details to be shown : yes or no")
while a == "yes":
    b = input('--enter the name to search--')
    if b in name:
        c = name.index(b)
        print('\n')
        print("      Name : ", name[c])
        print("      Mobile number : ", mob[c])
        print("      Email id :", email[c])
        break
    else:
        print("name is not found in the  contact list")
        continue

# delete contact details
b=input("Do you want to delete any person's contact details : yes or no  ")
while b == "yes":
    c=input('--enter the name to delete--')
    if c in name:
        l = name.index(c)
        name.pop(l)
        mob.pop(l)
        email.pop(l)
        print("contact details have been deleted successfully")
        i=0
        while i<len(name):
            print("\n")
            print("Name :", name[i])
            print("Mob number :", mob[i])
            print("Email : ", email[i])
            i+=1
        break
    else:
        print("name is not found in the contact list")
        continue



x=input()
y=list(map(str,x))
z=x.split("@")
l=z[1].split(".")
print(l)
print(z)

file1=open("nirma.txt","w")
file1.write("aaaaaa")
file1.close()
file1=open("nirma.txt","w")
file1.write("bbbbb")
file1.close()

file1=open("nirma.txt","w")
t=["first\t",'sencon\n',"thirs"]
file1.writelines(t)



import os
os.mkdir("data")

import os
os.rmdir("ds")

import os
os.mkdir("d29"/"guvi"/"nirmal")

from google.colab import drive
drive.mount('/content/drive')

"""# New Section

# New Section

# New Section
"""

import math
x=int(input())
y=math.factorial(x)
print(y)

x=lambda a,b:a**b
print(x(5,2))

def fun(n):
  return lambda a:a*n
x=fun(5)
print(x(10))

x=[5,12,13,14,15,18,20,21,22]

y=list(filter(lambda y: True if(y>18)   else False ,x))
print(y)

s=[1,2,3,4,5,6,7,8,9]
x=list(filter(lambda a: a%2==0,s))
print(x)
y=list(filter(lambda a: a%2!=0,s))
print(y)

z=["cat","dog","mouse"]
x=list(map(lambda y:y.upper(),z))
print(*x)

def gun(a,b):
  return a+b
x=list(map(lambda a,b:a+b,("rajini","kamal","thala"),("kanth","hasan","pathy")))
print(x)

a="    arun kumar guvi"
a.strip()

x={2:"arun",3:[1,2,3],"name":"kumar"}
x.pop(2)
print(x)

hello()

class up:
  x="arun"
a=up()
print(a.x)

class guvi:
  def __init__(self,fname,sname):
    self.f1=fname
    self.s1=sname
  def mt(sel):
     return sel.f1.upper()
x=guvi("arun","kumar")
print(x.f1,x.s1)
x.mt()

def hello():
  print("arun kumr")
  print("7y89u9") 
hello()

x=input()
y=x[::-1]
if x==y:
  print("yes")
else:
  print("no")

date=input()
dd,mm,yy=map(int,date.split(' '))
print(dd,mm,yy)
print(type(dd))

a="458"
b=a[2:]
print(b)

name=input("enter 5 names").split()
mob=list(map(int,input("enter 5 mobile numbers").split()))
email=input("enter 5 emailid").split()
contact=[]
contact.append(list(list(name)))
contact.append(list(list(mob)))
contact.append(list(list(email)))

a=input("enter a option any option 1. to on")
b=name.index(a)
print(name[b],mob[b],email[b])

name=[]
mob=[]
email=[]
n=int(input("enter total no of contacts to be stored : "))
for i in range(n):
    a=input("enter name:")
    name.append(a.capitalize())
    while True:
        b = input("enter mobile number :")
        if len(b) == 10 and b.isdigit():
            mob.append(b)
            break
        else:
            print("-----------enter a correct mobile number------------")
            continue

    while True:
        e = input("enter email id :")
        l=list(map(str,e))
        c = e.split("@")
        if "@" in l and "gmail.com" in c and c[0].isalpha():
            email.append(e)
            break
        else:
            print("-----enter a correct e-mailid of gmail account-----")
            continue



print(email)

def add(a,b):
  return a+b
def mul(a,b):
  return a*b
def div(a,b):
  return a/b
def sub(a,b):
  return a-b
x,y=map(int,input("give 2 numbers").split())
z=input("wat to do")
if z=="add":
  c=add(x,y)
  print(c)
elif z=="sub":
  c=sub(x,y)
  print(c)
elif z=="mul":
  c=sub(x,y)
  print(c)
elif z=="div":
  c=sub(x,y)
  print(c)

x=100
def func():
  global x
  x=x*2
  print(x)
print(x)
func()
print(x)

def fool(*ku):
  print(*ku)
fool(1,"arun",4,'kumar')

def my(**aru):
  print(**aru)
my(1=2,2=3)

x=int(input())
if x%4==0:
  print("YES")
else:
  print("NO")

x=input()
k=[]
a=[]
for i in x:
  if i not in k:
    k.append(i)
  else:
    a.append(i)
if len(k)==len(a):
  print(1)
else:
  print(0)

x=int(input())
k=[]
for i in range(2,x):
  if x%i==0:
    k.append(i)
if len(k)>0:
  print("yes")
else:
  print("no")

x=int(input())
k=[]

if x%11==0:
  k.append(x)
if len(k)>0:
  print("YES")
else:
  print("NO")

x=int(input())
k=[]

if x%11==0:
  k.append(x)
if len(k)>0:
  print("YES")
else:
  print("NO")

x=int(input())
k=[]

if x%11==0:
  k.append(x)
if len(k)>0:
  print("YES")
else:
  print("NO")

x,y=map(int,input().split())
k=[]
for i in range(x,y+1):
  if i%2!=0:
    k.append(i)
print(sum(k))

x=int(input())
k=[]
for i in range(2,x+1):
  if i%2==0:
    if x%i==0:
      k.append(i)
if len(k)>0:
  print(*k)
else:
  print(-1)



i=0
while i<6:
  i+=1
  if i==3:
    continue
  print(i)

i=1
j=1
while j<10:
  while i<6:
    print(i)
    if i==3:
      continue
    i+=1
  j+=1

for i in range(-30,-1,+1):
  print(i)

x=int(input())
k=[]
i=0
while i<x:
    j=input()
    if j:
        k.append(j)
        i+=1
a=["a","e","i","o","u"]
b=[]
for i in k:
    j=list(map(str,i))
    b.append(j)
h=[]
for i in b:
    for j in i:
        if j in a:
            h.append(i)
            break
if len(b)==len(h):
    print("yes")
else:
    print("no")



x=input()
y=list(map(str,x))
k=[]
for i in y:
  if i not in k:
    k.append(i)
i=0
a=[]
while i<len(k):
  x=y.count(k[i])
  a.append(x)
  i+=1 
f=[]
for i,j in zip(k,a):
  f.append(str(i))
  f.append(str(j))
j=''
j=j.join(f)
print(j)